global:
  # global values used by both helm charts
  serviceAccount:
    controller:
      # Specifies whether a service account should be created
      create: true
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, the default will be "landscaper"
      name: ""

    webhooksServer:
      # Specifies whether a service account should be created
      create: true
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, the default will be "landscaper-webhooks"
      name: ""

    user:
      # Specifies whether a service account should be created
      create: false
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, the default will be "landscaper-user"
      name: ""

#landscaper:
  # landscaper helm chart values

#rbac:
  # rbac helm chart values
