apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: application-nginx-ingress-controller

spec:
  blueprint:
    ref:
      repositoryContext: #maybe optional
        baseUrl: "eu.gcr.io/gardener-dev/"
        type: ociRegistry

      version: "v0.2.0"
      componentName: "github.com/gardener/external-dns-management"
      kind: "localResource"
      resourceName: "installation"
    inline:

      blueprint.yaml:
        apiVersion: landscaper.gardener.cloud/v1alpha1
        kind: Blueprint
        imports: ....

  # imported data objects that have to be defined in the system
  # either by the operator or exported by another installation.
  imports:
    data:
    - name: dnsClass
      dataRef: "application-dnsClass"

    - name: namespace
      dataRef: "application-namespace"

    targets:
    - name: cluster
      target: "dev-cluster"

  importDataMappings:
    identifier: my-gardener-dns
    namespace: (( installation.imports.namespace )) # optional, will be defaulted
    dnsClass: (( installation.imports.dnsClass )) # optional, will be defaulted

  exports:
    targets:
    - name: exported-cluster
      target: application-cluster
---
kind: DataObject
metadata:
  name: application-ingressClass
  ownerReferences:
  - kind: Installation
    name: application-nginx-ingress-controller
data: "myingressclass"
---
kind: Target
metadata:
  name: application-cluster
  lables: {}
  annotations: {}
spec:
  type: "landscaper.gardener.cloud/kubernetes-cluster"
  config:
    kubeconfig: |
      apiVersion: ....
---