{{/* SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.agent.registryConfig.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "landscaper.fullname" . }}-registry
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.agent.registryConfig.secrets }}
  {{ $key }}: {{ toJson $value | b64enc }}
  {{- end }}
{{- end }}
