{{/* SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}
{{- if not (has "all" .Values.webhooksServer.disableWebhooks) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "landscaper.webhooks.fullname" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhooksServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "landscaper.webhooks.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{ range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value}}
        {{- end }}
      labels:
        {{- include "landscaper.webhooks.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "landscaper.webhooks.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "landscaper-webhook-image" . }}"
          imagePullPolicy: {{ .Values.webhooksServer.image.pullPolicy }}
          args:
          {{- if .Values.webhooksServer.clusterKubeconfig }}
          - "--kubeconfig=/app/ls/landscaper-cluster-kubeconfig/kubeconfig"
          - --webhook-url=https://{{ include "landscaper.webhooks.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.webhooksServer.servicePort }}
          - --certificates-namespace={{ .Values.webhooksServer.certificatesNamespace }}
          {{- else }}
          - --webhook-service={{ .Release.Namespace }}/{{ include "landscaper.webhooks.fullname" . }}
          - --webhook-service-port={{ .Values.webhooksServer.servicePort }}
          {{- end }}
          - "-v={{ .Values.landscaper.verbosity }}"
          - --port={{ .Values.webhooksServer.servicePort }}
          {{- if .Values.webhooksServer.disableWebhooks }}
          - --disable-webhooks={{ .Values.webhooksServer.disableWebhooks | join "," }}
          {{- end }}
          {{- if .Values.webhooksServer.clusterKubeconfig }}
          volumeMounts:
          - name: landscaper-cluster-kubeconfig
            mountPath: /app/ls/landscaper-cluster-kubeconfig
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.webhooksServer.clusterKubeconfig }}
      volumes:
      - name: landscaper-cluster-kubeconfig
        secret:
          {{- if .Values.webhooksServer.clusterKubeconfig.kubeconfig }}
          secretName: {{ include "landscaper.fullname" . }}-webhooks-cluster-kubeconfig
          {{- else }}
          secretName: {{ .Values.webhooksServer.clusterKubeconfig.secretRef }}
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}