{{/* SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.landscaper.deployersConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "landscaper.fullname" . }}-deployers-config
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
data:
  deployers-config.yaml: {{ toYaml .Values.landscaper.deployersConfig | nindent 4 }}
{{- end }}