{{- if .Values.landscaper.registrySecrets.blueprints }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "landscaper.fullname" . }}-registry-blueprints
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.landscaper.registrySecrets.blueprints }}
  {{ $key }}: {{ toJson $value | b64enc }}
  {{- end }}
{{- end }}
{{- if .Values.landscaper.registrySecrets.components }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "landscaper.fullname" . }}-registry-components
  labels:
  {{- include "landscaper.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.landscaper.registrySecrets.components }}
  {{ $key }}: {{ toJson $value | b64enc }}
  {{- end }}
{{- end }}