{{/* SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "landscaper.fullname" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if not (has "all" .Values.disableWebhooks) }}
    - port: {{ .Values.webhookConfig.servicePort }}
      targetPort: {{ .Values.webhookConfig.serverPort }}
      protocol: TCP
      name: webhook
    {{- end }}
  selector:
    {{- include "landscaper.selectorLabels" . | nindent 4 }}
